### ISSUE TITLE
<noscript> does not support dataLayer variables

### ISSUE THREAD

**Issue by wojciechczerniak** [spatie/laravel-googletagmanager#12]
DataLayer variables should be added to iframe URL as query parameters.

Docs: https://developers.google.com/tag-manager/devguide#adding-data-layer-variables-for-devices-without-javascript-support

Example snippet from docs:

    
    <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-XXXX&pageCategory=sports&visitorType=returning" height="0"
                  width="0" style="display:none;visibility:hidden"></iframe></noscript>

**Comment by sebastiandedeyne** [comment]
We'd accept a PR that adds this.

**Comment by freekmurze** [comment]
We'll discuss this further in #18

**Comment by technicaljunkie** [comment]
So its a bug
