### ISSUE TITLE
Split @include('googletagmanager::script') into two parts

### ISSUE THREAD

**Issue by wojciechczerniak** [spatie/laravel-googletagmanager#13]
According to GTM docs (https://developers.google.com/tag-manager/quickstart) `<script>` should be placed "as close to the opening `<head>` tag as possible" and `<noscript>` part "immediately after the opening `<body>` tag". 

Simo Ahava explains reasoning behind this: https://www.simoahava.com/gtm-tips/gtm-container-snippet-in-the-head/

**Comment by freekmurze** [comment]
This is a breaking change. I'll revisit this when creating the next major version. Might take a while though.
