### ISSUE TITLE
How to use different Environments

### ISSUE THREAD

**Issue by KHucks** [spatie/laravel-googletagmanager#2]
Google now offers to use different Environments for the GTM code (GTM-ID ID is the same for all environments -> gtm_auth and gtm_preview are specific to the environments)
It seems that the customizing options only allow to set ID and enable/disable.

Has anyone implemented it using these options yet? How? 

The objective is to also use GTM on Stage and Testing Environments but separate the data from Production (obviously).

**Comment by sebastiandedeyne** [comment]
Environments currently aren't supported in this package. I most likely won't be adding this any time soon, but I'd accept a PR that adds this to the configuration.
