### ISSUE TITLE
Non-static method should not be called statically

### ISSUE THREAD

**Issue by barryvanveen** [spatie/laravel-googletagmanager#3]
Good evening!

I just tried to install this package and immediately ran into this error. It seems like the methods on the facade are not static, but according to the readme they should be called statically.

My controller contains a call to the set-method like 

    use Spatie\GoogleTagManager\GoogleTagManager;
    
    class Controller extends BaseController
    {
    
        public function __construct()
        {
            GoogleTagManager::set('pageType', 'productDetail');

Which results in the following error: `Non-static method Spatie\GoogleTagManager\GoogleTagManager::set() should not be called statically`

It feels like I'm missing something obvious because the readme is so clear about how to call the facade. Could someone please have a look?

-- Barry

**Comment by sebastiandedeyne** [comment]
Hi!

If you're using the facade, you need to import it without the namespace (otherwise you're just importing the class itself).

```
use GoogleTagManager;

class Controller extends BaseController
{
    ....
```

**Comment by barryvanveen** [comment]
Thank you Sebastian, that was it!

**Comment by dipenparmar12** [comment]
One more thing we can call any method statically using facades 
just prefix 'Facades\' in namespace 
for Example

`
namespace Facades\App\Http\YourClassName;
`
> now you can use any method statically of `YourClassName` class 
> ` YourClassName::methodName(params)`


ref ([Real time laravel Facades](https://laravel.com/docs/master/facades#real-time-facades))
