### ISSUE TITLE
Is it possible to push events after gtm?

### ISSUE THREAD

**Issue by Nazalas** [spatie/laravel-googletagmanager#31]
Is it possible to use this package to push events after the gtm code has been fired off. For example.

0: {event: "impressionsExample", gtm.uniqueEventId: 0}
1: {gtm.start: "123456789", event: "gtm.js"m gtm.uniqueEventId: 1}
2: {event: "gtm.dom", gtm.uniqueEventId: 2}
3: {event: "gtm.load", gtm.uniqueEventId: 3}
4: {event: "loginExample", gtm.uniqueEventId: 4}

Would it be possible to use this package for the loginExample event?

**Comment by sebastiandedeyne** [comment]
Since this package's code gets executed on the server, we can't do anything after load. You'll need to use JavaScript for this.
