### ISSUE TITLE
Please dont overwrite dataLayer in head.

### ISSUE THREAD

**Issue by AndreasGJ** [spatie/laravel-googletagmanager#32]
https://github.com/spatie/laravel-googletagmanager/blob/aadef9d3fc9ced1a8ab03a91ddab59979644182c/resources/views/head.blade.php#L4

Please update the code to do a push instead, then we can attach other dataLayer related data before the head component - like Google Optimize and more. I would also like to setup data in the dataLayer before the GTM is started rendering directly in the layout file.

```
dataLayer.push( {!! $dataLayer->toJson() !!} ); 
```

**Comment by tdondich** [comment]
@AndreasGJ one way you can do this, which I've done is simply override the vendor view files for the head blade template and inserted google optimize code after the dataLayer definition.  Works like a charm.  So this is totally doable.

**Comment by FrittenKeeZ** [comment]
@AndreasGJ I've finally added a PR (#40) for this fix :D
