### ISSUE TITLE
GTM Multiple environment snippet support

### ISSUE THREAD

**Issue by danielsimkus** [spatie/laravel-googletagmanager#34]
Hello,

I've recently had to overwrite the googletagmanager body & head templates to add in additional parameters `gtm_auth` and `gtm_preview` in order to support [multiple GTM environments](https://support.google.com/tagmanager/answer/6311518?hl=en). Just wondering if this is something you'd be interested in adding?

I can potentially submit a PR if required?

**Comment by lptn** [comment]
hey @danielsimkus 
Have you received an answer? I will probably also use envs with GTM and can create a PR for that
