### ISSUE TITLE
multiple domains

### ISSUE THREAD

**Issue by isomis** [spatie/laravel-googletagmanager#4]
I want to set tag manager id trough a function. Can you make that?

**Comment by sebastiandedeyne** [comment]
It currently isn't possible since the id gets set in the `GoogleTagManager` class' constructor. I'd accept a PR that retrieves the id on the fly from Laravel's config instead, so it's more flexible.

**Comment by davidgv88** [comment]
Solved! I have created a ConfigServiceProvider and added this:

app('Spatie\GoogleTagManager\GoogleTagManager')->setId('GTM-XXXXX');

GTM-XXXX is different depending on the domain
