### ISSUE TITLE
Small error in readme

### ISSUE THREAD

**Issue by barryvanveen** [spatie/laravel-googletagmanager#5]
In the readme it states that the "enabled" configuration can be set like this:
`
    'enabled' => app()->environment() === 'production',
`

This causes the following error, probably because the environment is not yet set at this point:

> Fatal error: Uncaught ReflectionException: Class env does not exist in /home/vagrant/Code/barryvanveen/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 734
> ReflectionException: Class env does not exist in /home/vagrant/Code/barryvanveen/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 734

I believe a better way to use this would be:
`
    'enabled' => env('APP_ENV') === 'production',
`

Could this be fixed in the readme to help new users?

Cheers,

Barry

**Comment by sebastiandedeyne** [comment]
Fixed 👍
