### ISSUE TITLE
DataLayer escapes unicode characters

### ISSUE THREAD

**Issue by amraei** [spatie/laravel-googletagmanager#7]
For non-english websites data layer escapes unicode characters and causes bad product names in Analytics. Like this:

`"impressions":[{"id":73,"name":"\u0643\u0648\u0633\u0646 \u06af\u0648\u0646\u06cc \u067e\u0648\u0634"]}`

It happens in `Spatie\GoogleTagManager\DataLayer` class which:

`return json_encode($this->data);`

should be replaced with:

`return json_encode($this->data, JSON_UNESCAPED_UNICODE);`

**Comment by sebastiandedeyne** [comment]
Thanks for reporting! This has been fixed in `2.2.3'.
