### ISSUE TITLE
GTM Code in Controller not firing

### ISSUE THREAD

**Issue by robplsykes** [spatie/laravel-googletagmanager#8]
Hey, i'm not sure if this is just my setup, but i'm working on an application that needs to firing some purchase information off once the user has proceed through the checkout. I have created a macro and called that in the controller method that is being fired.

I can see from my debugging that this is actually being called but when I look at the tag manager debug and tag assistant I cannot see the data layer being sent across. 

On the other hand if I make this call in the view, it fires successfully. For reasons, I need to be able to make these calls via the controller.  I have the tags set up in tag manager to fire on an event rather than a page view so in theory it should work. 

I'm not sure what info, snippets you might need so i'll just post the code for the macro and macro call. If there is anything else required, let me know. I'm honestly quite stumped with this.

```php
GoogleTagManager::macro('purchase', function($order, array $products) {
    GoogleTagManager::set('event','transaction');

    GoogleTagManager::set('ecommerce.purchase.actionField',
        [
            'id' => $order->id,
            'affiliation' => '',
            'revenue'=> number_format($order->order_total, 2),
        ]);

    foreach($products as $product) {
        $product = (object) $product;

        GoogleTagManager::set('ecommerce.purchase.products', [
            [
                'name' => $product->name . ' - ' . number_format($product->unit_price, 2),
                'id' => $product->model_id,
                'price' => number_format($product->unit_price, 2),
                'brand' => '',
                'category' => $product->isVoucher ? 'Voucher' : 'Product',
                'quantity' => $product->quantity
            ]
        ]);
    }
});
```

And the call in the controller

```php
GoogleTagManager::purchase($order, $basket->getLines()->toArray());
```

Thanks in advance.

**Comment by sebastiandedeyne** [comment]
Don't see anything wrong at first site. What does the DataLayer output script look like? (in your rendered html source, not Google's debugger)

**Comment by robplsykes** [comment]
Hey Sebastian, 

The only thing that is currently being rendered is this : 

```
<script>
window.dataLayer = window.dataLayer || [];
dataLayer = [[]];
</script>
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-MPB83P7"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-XXXXXXX');</script>
```

I've omitted the GTM tag. But it is a 7 digit GTM tag (not that I think that would have anything to do with it.) I have noticed that when I updated the data layer via purchase it doesn't seem to reflect this in the rendered HTML. i.e. dataLayer = [[]]; still remains empty regardless.

**Comment by robplsykes** [comment]
However, taking a look at the output of `GoogleTagManager::getDataLayer()->toJson` outputs the correct json. But only when done in the controller. Inside any views it returns empty.

**Comment by robplsykes** [comment]
I've discovered that the issue is with `return redirect();`. I'm trying to set the datalayer in a post method which redirects to another url (in this case order-confirm). If I return a view this works perfectly, however, I do need to redirect  rather than return a view from posts because of the urls.

**Comment by sebastiandedeyne** [comment]
The `set` method only works with the current request. If you're doing a redirect, try replacing all `set` calls with `flash`, for example `GoogleTagManager::flash('ecommerce.purchase.actionField', [])`

**Comment by robplsykes** [comment]
Brilliant. That worked. Thanks Sebastian.
